Algoritmo "primeiroalgoritmo"
// Disciplina  : [Curso VisualGUdemy]
// Professor   : Rafael Gomes
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leila Oliveira
// Data atual  : 21/09/2021
Var
// Seção de Declarações das variáveis 
   n1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para n1 de 1 ate 50 faca
   escreval(n1)
   fimpara

Fimalgoritmo